# Generated by Django 4.2.3 on 2023-07-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpost_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='full_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
