# Generated by Django 4.2.3 on 2023-07-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userpost_alamat_alter_userpost_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='full_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
