# Generated by Django 4.2.3 on 2023-07-27 05:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpost_alamat_alter_userpost_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='alamat',
            field=models.ImageField(blank=True, upload_to=users.models.content_file_name),
        ),
    ]
