# Generated by Django 4.2.3 on 2023-07-27 05:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpost_bio_alter_userpost_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='alamat',
            field=models.TextField(blank=True),
        ),
    ]
