# Generated by Django 4.2.3 on 2023-07-27 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_userpost_image_alter_userpost_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='username',
        ),
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userpost', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
