# Generated by Django 4.2.3 on 2023-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='is_publis',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
