# Generated by Django 4.2.3 on 2023-07-22 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogpostmodel_is_publis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
