# Generated by Django 4.2.3 on 2023-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostmodel_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
