# Generated by Django 4.2.3 on 2023-07-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpostmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='is_publis',
        ),
    ]
