# Generated by Django 4.2.3 on 2023-07-25 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_blogpostmodel_is_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='publishAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
