# Generated by Django 4.2.3 on 2023-07-25 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_blogpostmodel_publishat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='publishAt',
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
